name: Publish docs to GitHub Pages

on:
  workflow_call:
    inputs:
      destination_dir:
        required: true
        type: string

jobs:
  upload-docs:
    name: Upload docs as artifact
    runs-on: ubuntu-latest
    steps:
      - name: Ensure `destination_dir` is not empty
        if: ${{ inputs.destination_dir == '' }}
        run: exit 1
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Get Yarn cache directory
        run: echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"
        id: yarn-cache-dir
      - name: Get Yarn version
        run: echo "YARN_VERSION=$(yarn --version)" >> "$GITHUB_OUTPUT"
        id: yarn-version
      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
          key: yarn-cache-${{ runner.os }}-${{ steps.yarn-version.outputs.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
      - name: Install npm dependencies
        run: yarn --immutable
      - name: Run build script
        run: yarn build:docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs
  publish-docs-to-gh-pages:
    name: Publish docs to GitHub Pages
    runs-on: ubuntu-latest
    needs: upload-docs
    environment:
      name: github-pages
      url: ${{ inputs.destination_dir }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to `${{ inputs.destination_dir }}` directory of `gh-pages` branch
        uses: actions/deploy-pages@v1



